name: Cleanup Untagged Images

on:
  schedule:
    - cron: "0 3 1 * *" # 1st of every month at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "database-backup"
          tag-selection: untagged
          cut-off: 1d
          dry-run: false
